#!/bin/sh
#

module_load() {
	local modname

	modname=$1
	shift

	printf "modprobe $modname: "

	modprobe $modname $@
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

module_unload() {
	printf "rmmod $1: "
	rmmod $1
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

start() {
	echo "Loading Prestera Switchdev platform drivers ..."
	module_load gpio_i2c
	umask 077
}

stop() {
	echo "Unloading Prestera Switchdev platform drivers ..."
	module_unload gpio_i2c
}

restart() {
	stop
	sleep 1
	start "$@"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  force-reload)
	restart -R
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}"
	exit 1
esac

exit $?
