# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Marvell Switch driver.
#
obj-$(CONFIG_PLAT_GPIO_I2C) += gpio_i2c.o
obj-$(CONFIG_PLAT_TN48XXM_CPLD) += tn48xxm-cpld.o
obj-$(CONFIG_PLAT_AS5114_48X_CPLD) += as5114-48x-cpld.o
